### ISSUE TITLE
Config error not handled

### ISSUE THREAD

**Issue by jjcf89** [MajorMJR/factorio-server-manager#17]
Getting the following json response for configuration page:

```
success:false
data:"Error getting config.ini"
```

Page shows it as if each letter in data was a separate config, instead of showing an error message.

**Comment by MajorMJR** [comment]
Is this running in a Docker container or on the base system?  It sounds like the UI program has no read access to the config.ini file.

Can you check your log if there are any more detailed errors?

**Comment by jjcf89** [comment]
This is in the docker container.

logs:
```
2016/04/30 01:10:58 Loading config file: /opt/factorio/config/config.ini
2016/04/30 01:10:58 Error loading config.ini file: open /opt/factorio/config/config.ini: no such file or directory
...
2016/04/30 01:12:35 Error reading mod-list.json file: open /opt/factorio/mods/mod-list.json: no such file or directory

```

**Comment by MajorMJR** [comment]
hmm has the Factorio server been launched yet?  Maybe when the Docker container is first launched these functions wont work since the config file and mod-list.json file haven't been generated.

Can you run
`docker exec -ti factorio-server /bin/sh`
and run ls on the /opt/factorio directory?

**Comment by jjcf89** [comment]
No config file
```
$ docker exec -it factorio-server ls /opt/factorio
bin                   data                  mods
config-path.cfg       factorio-current.log  saves
```

**Comment by jjcf89** [comment]
I manually copied the save file and ran server.  This created the config directory and file.

```
$ docker exec -it factorio-server ls /opt/factorio/saves
_autosave12.zip
$ docker exec -it factorio-server /opt/factorio/bin/x64/factorio --start-server _autosave12
...
$ docker exec -it factorio-server ls /opt/factorio/
bin                    factorio-current.log   saves
config                 factorio-previous.log  temp
config-path.cfg        mods
data                   player-data.json
```

So two problems:
* The server must be started before the config is created. Solved
* The config tag doesn't handle a success: false
