### ISSUE TITLE
Consider using Equinox or other release tool

### ISSUE THREAD

**Issue by willglynn** [MajorMJR/factorio-server-manager#2]
[Equinox](https://equinox.io) handles a lot of open problems:

* Builds the binaries for many target platforms
* Creates installers appropriate for each target platform
* Combines the result into a [pretty install page](https://dl.equinox.io/equinox/release-tool/stable)
* Makes it [trivial to self-update after installation](https://equinox.io/docs#updating)

See also [the blog post](https://inconshreveable.com/04-26-2016/launching-equinox-and-the-importance-of-software-packaging/) announcing Equinox. It's free for open-source tools, and signing in with GitHub instantly gets you a sandbox account to try it out.

I have no particular connection to Equinox, and there are some other options in this space. I think FSM should use one of them.

**Comment by MajorMJR** [comment]
I think it might be better to use a more general build tool such as Travis in order to get some CI features also.

**Comment by willglynn** [comment]
This would be complimentary to CI. Travis would handle making sure nothing broke during development (pushing commits and evaluating PRs), while Equinox would handle user-facing releases (downloads and updates).

**Comment by MajorMJR** [comment]
I read a bit more about Equinox and I see what you mean.  This could help deployment to users in the future if there are many new versions of the server manager.  If someone has a deployed server updating may be easier for them.

Another option might be to make the application build in a Dockerfile and distribute the application through Docker Hub.
