### ISSUE TITLE
Poorly formatted server started dialog

### ISSUE THREAD

**Issue by jjcf89** [MajorMJR/factorio-server-manager#20]
After starting server I see dialog stating: `Factorio server started on port: %!s(int=34197)`

**Comment by MajorMJR** [comment]
This is fixed in 0.3

**Comment by jjcf89** [comment]
Aww missed that.  I pulled the latest docker version but didn't notice `MANAGER_VERSION=0.2.0` hadn't been updated.

**Comment by MajorMJR** [comment]
ah thank you I forgot the update the Dockerfile.

Fixed in 32c9c53acc27179e3a7c9cfca40864be172ce179
