### ISSUE TITLE
docker: allow to disable basic auth

### ISSUE THREAD

**Issue by drahti** [MajorMJR/factorio-server-manager#22]
I wanted to add this to the backlog and also discuss it before I start working on it.

With the ability of authentication from the manager itself, authenticating from the proxy is no longer strictly necessary, am I correct?

However, to my ignorant eyes it looks like the manager only allows for one user? For this reason basic auth might still be of use for some people, so it should be made optional, but not removed?

Now tell me where I am wrong and what to do :)

**Comment by MajorMJR** [comment]
Hi @drahti 

Yeah currently only a single user is supported from the UI.  So it would probably be best to have the HTTP auth be optional like you said incase a user wants to have multiple users.

Next release should add the ability to manage multiple users.

**Comment by jjcf89** [comment]
Tried commenting out the auth_basic and auth_basic_user_file lines in the nginx.conf file but then I was unable to login on the FSM login page, due to a error returned by nginx.

**Comment by MajorMJR** [comment]
What was the error from Nginx?

**Comment by jjcf89** [comment]
Does the go webserver support ssl?  Is the nginx server necessary anymore?

| What was the error from Nginx?
There was no visible error, the page just returned to the login page.  In the network tab there was a response from nginx that I think said 405 error but I don't remember.  I reverted the change and can't look now.

**Comment by MajorMJR** [comment]
It doesn't support SSL right itself right now, so having the reverse proxy for people wanting to run the server on a public server is still useful IMO.

**Comment by jjcf89** [comment]
Okay good to know. Should be a way to disable the nginx auth and keep the SSL.  Just not as familiar with nginx as I thought...

**Comment by bostelk** [comment]
basic auth has been removed. this can be closed.

**Comment by MajorMJR** [comment]
Basic Auth was removed by @bostelk as I've implemented authentication in the application.
