### ISSUE TITLE
Permissions check

### ISSUE THREAD

**Issue by jarvis2point0** [MajorMJR/factorio-server-manager#23]
Using the release, couldn't toggle the mods as the mods-list.json file wasn't owned by the user executing the factorio-server-manager. All mods and game files and saves belonged to the correct user, however the single file mods-list.json was owned by another user, causing the problem where when you toggle the availibility of any given mod, mods-list.json could not be modified.

**Comment by MajorMJR** [comment]
Causes bug in the UI:  http://i.imgur.com/JXAUma1.gifv

Server ouput: 
2016/05/02 19:24:38 Error writing to mod-list.json file: open /home/factorio/factorio/mods/mod-list.json: permission denied
2016/05/02 19:24:38 Mod: base was toggled to false

Need to add check if there are read permissions on files in Factorio directory.  Send error message for UI to display if not.

**Comment by MajorMJR** [comment]
This is fixed, proper error handling was added to give the user an error message.
