### ISSUE TITLE
Failure to create files/folders

### ISSUE THREAD

**Issue by bloons3** [MajorMJR/factorio-server-manager#31]
`2016/05/21 14:28:46 Error reading mod-list.json file: open /home/bloons3/factorio/mods/mod-list.json: no such file or directory

2016/05/21 14:28:46 Error listing installed mods: open /home/bloons3/factorio/mods: no such file or directory

2016/05/21 14:29:00 Error reading mod-list.json file: open /home/bloons3/factorio/mods/mod-list.json: no such file or directory

2016/05/21 14:29:00 Error listing installed mods: open /home/bloons3/factorio/mods: no such file or directory

2016/05/21 14:30:30 Error reading mod-list.json file: open /home/bloons3/factorio/mods/mod-list.json: no such file or directory`

Fails to create needed files, the /home/bloons3/factorio folder is owned by the user that the server is running as

**Comment by MajorMJR** [comment]
Make sure the Factorio server is started atleast once to create the necessary files.

**Comment by bloons3** [comment]
The factorio server was started. Also, config.ini didn't work until I
'touched' it to create it in the factorio directory
