### ISSUE TITLE
Docker - Unauthenticated request GET <host> /api/user/status

### ISSUE THREAD

**Issue by anup-ap** [MajorMJR/factorio-server-manager#32]
Attempting to use the Docker container and after completing basic auth and then user login, the page redirects to the login.  ```docker logs <container_name>``` returns the error 
```Unauthenticated request GET <host> /api/user/status```

One possibility was an error due to the password in /opt/factorio-server/conf.json was somehow conflicting with the login credentials but that's a weak guess at best.  Attempting to use the same password didn't work.

A second idea was that the hash generated by OpenSSL in my local environment was not compatible with the hash generated by OpenSSL within the alpine envinronment.  The docker build works but openssl is not installed so the normal initialization doesn't work.

**Comment by MajorMJR** [comment]
The basic HTTP authentication was implemented before I added in the user management features.  Unfortunately I haven't had much time to test the Docker container with the authentication. 

If you are building the Docker container you can try and comment out the Nginx configuration for the basic auth.  It shouldn't be needed now as the application itself has user authentication now.

**Comment by anup-ap** [comment]
Basic auth is working fine, albeit annoying.  I was going to remove it but it was useful to validate that the env var for ADMIN_PASSWORD was being used properly.  The error seems to be the Go back-end reporting an auth failure and I wasn't sure how to solve for that.

I'll try fiddling with the Dockerfile image again but any pointers re: why the back-end might be failing the auth check when nginx is reading the same credentials would be appreciated.

**Comment by jjcf89** [comment]
> I'll try fiddling with the Dockerfile image again but any pointers re: why the back-end might be failing the auth check when nginx is reading the same credentials would be appreciated.
It was my understanding that the nginx auth and the go auth use separate credentials. i.e. the openssl hash nginx uses isn't used by the go auth.

**Comment by MajorMJR** [comment]
Yeah credentials should be separate.  The Docker image uses the ADMIN_PASSWORD environment variable and the built-in authentication would be configured in the conf.json file.

**Comment by cocazoulou** [comment]
Hi @MajorMJR 
The issue with the Docker image seem to come from that both the UI answer to /login and the /api.
with Nginx those are separate pretty early.

I have been able to make it work by just updating the nginx.conf files. It's not pretty at all. It should be better to update the /login into the Golang part to /api/login and then update the ui one.

location / {
                if ($request_method = POST ) {
                        proxy_pass              http://127.0.0.1:8080;
                }

                root /opt/factorio-server/app;
                try_files $uri /index.html;
        }

**Comment by bostelk** [comment]
I just submitted a PR to fix this.

**Comment by MajorMJR** [comment]
I've merged @bostelk fixes for this.
