### ISSUE TITLE
Wrong savegame path

### ISSUE THREAD

**Issue by xlemmingx** [MajorMJR/factorio-server-manager#36]
Not sure if it depends on my setup, so i will describe it shortly:
~/factorio   contains factorio headless server with standard folder structure (bin, config, data, mods, saves) v13.8
~/factorio-server   contains unziped server manager files

Starting params runnning as user factorio2:
./factorio-server-manager --dir "/home/factorio2/factorio/" --port "9595"

Everyhing in the Manager works, including uploading Mods and Savegames (to the correct folder) EXCEPT for actually starting the server.
Error:
   3.749 Error MultiplayerManager.cpp:129: MultiplayerManager failed: "Opening zip /home/factorio2/factorio-server/savegame.zip failed: No such file or directory"
   3.749 Info MultiplayerManager.cpp:996: networkTick(0) mapTick(-1) changing state from(CreatingGame) to(InitializationFailed)
   3.750 Error Main.cpp:455: Couldn't load the game for MP: Opening zip /home/factorio2/factorio-server/savegame.zip failed: No such file or directory

Looks like he is looking for the savegame not in ~/factorio/saves but in ~/factorio-server ? If i manually copy the file i uploaded from ~/factorio/saves to ~/factorio-server everything goes well and server starts as it should.

Any suggestions for fixing that?

**Comment by MajorMJR** [comment]
Hey @xlemmingx 

Currently whichever directory you use with the --dir option will define the root.  So all the Factorio standard folders are used in this directory like saves, mods, etc.

Right now you can't specify a different save directory, I'll have to look into adding this ability.

**Comment by xlemmingx** [comment]
Thanks for your answer. 
Anyways it seems not be completely right, as i have mentioned everything works out in the directory i defined with --dir parameter except for loading the savegame (i chose in manager). It is trying to load it from ther server-manager root directory when i click "Start server".

**Comment by MajorMJR** [comment]
Hmm I'm not sure why it would use a different directory then the one you specify with --dir option.

The server is started with a save specified from the root directory and the save file name selected in the web UI.

`"--start-server", filepath.Join(config.FactorioSavesDir, f.Savefile),`

Where config.FactorioSavesDir is defined as:

`config.FactorioSavesDir = filepath.Join(config.FactorioDir, "saves")`

So whichever directory you select when starting the server is the only option the server manager should see.  Can you check you starting command and make sure it's the correct path?

**Comment by xlemmingx** [comment]
Tried a complete new install to verify i did not mess anything up. Still getting same error. For clarification here is the complete log i get when pressing "Start Server" in the Webinterface with a given savegame. For some reasons he is still looking in /factorio-server, not in /factorio/saves as he should.

`factorio3@xlemroot:~/factorio-server$ ./factorio-server-manager --dir "/home/factorio3/factorio" --port "9595"
2016/07/12 19:57:01 Created initial user: admin
2016/07/12 19:57:01 Could not create modpacks directory: mkdir /home/factorio3/factorio/modpacks: file exists
Starting server on: 0.0.0.0:95952016/07/12 19:57:08 Starting Factorio server.
2016/07/12 19:57:08 Starting Factorio server with settings: {"savefile":"Oesterreicher2.zip","latency":100,"autosave_interval":5,"autosave_slots":10,"port":34199,"disallow_cmd":false,"peer2peer":false,"auto_pause":false}
2016/07/12 19:57:08 Starting server with command:  /home/factorio3/factorio/bin/x64/factorio [--start-server Oesterreicher2.zip --latency-ms 100 --autosave-interval 5 --autosave-slots 10 --port 34199]
   0.000 2016-07-12 19:57:08; Factorio 0.13.8 (build 23239, linux64, headless)
   0.000 Operating system: Linux
   0.000 Program arguments: "/home/factorio3/factorio/bin/x64/factorio" "--start-server" "Oesterreicher2.zip" "--latency-ms" "100" "--autosave-interval" "5" "--autosave-slots" "10" "--port" "34199"
   0.000 Read data path: /home/factorio3/factorio/data
   0.000 Write data path: /home/factorio3/factorio
   0.000 Binaries path: /home/factorio3/factorio/bin
   0.041 Running in headless mode
   0.049 Loading mod core 0.0.0 (data.lua)
   0.064 Loading mod base 0.13.8 (data.lua)
   0.419 Checksum for core: 714099156
   0.419 Checksum for mod base: 1905699976
2016/07/12 19:57:09 Factorio server started on port: %!s(int=34199)
2016/07/12 19:57:09 Factorio server started on port: %!s(int=34199)
2016/07/12 19:57:09 Creating server status response
2016/07/12 19:57:09 Server status sent with data: map[status:running port:34199 savefile:Oesterreicher2.zip]
2016/07/12 19:57:09 Creating server status response
2016/07/12 19:57:09 Server status sent with data: map[status:running port:34199 savefile:Oesterreicher2.zip]
   1.973 Custom inputs active: 0
   1.975 Factorio initialised
   1.979 Info Router.cpp:558: Router peerID(65535) shutting down.
   1.979 Info Router.cpp:594: Router state -> Disconnected
   1.983 Info MultiplayerManager.cpp:996: networkTick(0) mapTick(-1) changing state from(Ready) to(PreparedToHostGame)
   1.983 Info MultiplayerManager.cpp:996: networkTick(0) mapTick(-1) changing state from(PreparedToHostGame) to(CreatingGame)
   1.983 Loading map /home/factorio3/factorio-server/Oesterreicher2.zip
   2.003 Error MultiplayerManager.cpp:129: MultiplayerManager failed: "Opening zip /home/factorio3/factorio-server/Oesterreicher2.zip failed: No such file or directory"
   2.003 Info MultiplayerManager.cpp:996: networkTick(0) mapTick(-1) changing state from(CreatingGame) to(InitializationFailed)
   2.004 Error Main.cpp:455: Couldn't load the game for MP: Opening zip /home/factorio3/factorio-server/Oesterreicher2.zip failed: No such file or directory
2016/07/12 19:57:10 Command exited with error: exit status 1
2016/07/12 19:57:10 Error starting Factorio server: exit status 1
`

**Comment by MajorMJR** [comment]
I'm not sure why it is still using the factorio-server directory that's odd.  Do you know how to check the POST data you submit when you click start server in the web UI?  If you could open the developer tools in your browser and check what data is getting sent to the server maybe that will give us a hint where the bug is coming from.

**Comment by xlemmingx** [comment]
I think thats what u want to see?
[http://imgur.com/KwxKePW](url)

**Comment by jjcf89** [comment]
I thought I remember someone else reporting this.  The server is passing the save file in as a relative path and a change in factorio now looks in the working directory which is the factorio-server folder.

2016/07/12 19:57:08 Starting server with command: /home/factorio3/factorio/bin/x64/factorio [--start-server Oesterreicher2.zip --latency-ms 100 --autosave-interval 5 --autosave-slots 10 --port 34199]

**Comment by xlemmingx** [comment]
So the fix would be to pass the absolute path generated from --dir parameter + "/save" towards the binary? Sounds easy.

**Comment by MajorMJR** [comment]
Yeah I think your right the full path is required which is causing this issue for you.  Luckily this was already fixed in #35.  I'll rebuild the binary and add a another bug fix release when I get home this evening.

**Comment by xlemmingx** [comment]
Nice, thank you very much for your awesome work!

**Comment by MajorMJR** [comment]
I can't take all the credit, thank @xeroiv for the bugfix

**Comment by MajorMJR** [comment]
I've added a new release 0.4.2 with the included fix. https://github.com/MajorMJR/factorio-server-manager/tree/0.4.2

**Comment by xlemmingx** [comment]
Works, thank you for fixing!

**Comment by MajorMJR** [comment]
Excellent glad to hear it.
