### ISSUE TITLE
Add docker file for application distribution

### ISSUE THREAD

**Issue by MajorMJR** [MajorMJR/factorio-server-manager#4]
Dockerfile will have to download latest release of Factorio server manager.  Then download headless server files and extract to a directory.  Dockerfile will specify ports for the Factorio game server and UI server.  Launch command will start Factorio Server Manager in order to allow user to start Factorio server from the UI.

**Comment by jjcf89** [comment]
#8 Linking pull request.

**Comment by jjcf89** [comment]
Would be interesting if the updater could be integrated into this docker image/server somehow.
https://github.com/narc0tiq/factorio-updater

Its currently used by https://github.com/Bisa/factorio-init

**Comment by drahti** [comment]
I'm not sure if the auto updater is actually needed. The container from #8 exposes mods and savegames as volumes. Once a new factorio version is released, you can basically just change the version in the Dockerfile, rebuild the image and run a new container with volumes mounted to the same place than the last one.

If you want to make it pretty, use a data-only container for mods and saves volumes. 

Factorio update would be done in... I guess 4 simple commands?

**Comment by jjcf89** [comment]
> Once a new factorio version is released, you can basically just change the version in the Dockerfile, rebuild the image and run a new container with volumes mounted to the same place than the last one.
Yeah I get that.  I suppose one of the benefits of the web ui though is I can allow my friends to manage saves and mods without me having to manually do so.  It would be nice if they could also update the factorio version from the web ui.

It now occurs to me that this is really a feature request that doesn't necessarily relate to this docker issue.

**Comment by MajorMJR** [comment]
Yeah an update feature could be implemented in the UI.  

It would only have to download the latest Factorio binary and replace it with the existing one.
