### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by bostelk** [MajorMJR/factorio-server-manager#46]
Might be nice to publish on Docker Hub once the dust has settled.

**Comment by MajorMJR** [comment]
I've published the docker file in this repo to Docker Hub, any commits to master will now rebuild the Docker container.

https://hub.docker.com/r/majormjr/factorio-server-manager/

**Comment by jjcf89** [comment]
Pretty cool. 

Will the section "Updating Factorio" in the docker hub work if they have retrieved their docker using docker pull instead of through github?

> To update Factorio you should then open the Dockerfile and change the Factorio version to the one desired. After that you need to rebuild the image using docker build -t factorio-server-manager .

**Comment by MajorMJR** [comment]
Probably not, that part of the readme still needs an update.  We could add a section for building the Docker container from scratch.
