### ISSUE TITLE
Save timestamp incorrect

### ISSUE THREAD

**Issue by cyris69** [MajorMJR/factorio-server-manager#57]
Not sure if there is somewhere to edit this in the configs but my times stamps are off by 2 days. So autosave just now says 2016-9-6 1:12:47 and today is 2016-9-8 and that actual zip file reflects it which is odd

**Comment by MajorMJR** [comment]
Check your system's time to make sure it's correct.  The timestamps are just using your own systems clock.

**Comment by TechnoNerdDad** [comment]
It appears to me that the saves date is using a zero-based index for the month and the day-of-the-week number for the day.

**Comment by MajorMJR** [comment]
Saves are created here: https://github.com/MajorMJR/factorio-server-manager/blob/master/src/saves.go#L63

There's no formatting of the time, whatever time is set on your system will be used.

**Comment by TechnoNerdDad** [comment]
This bug is not simply relative to the createSave() function.

On my Windows server, the files located in the 'saves' folder have the correct date. However, when displayed in the UI, the date does not coincide and appears as I mentioned in my previous comment.

**Comment by MajorMJR** [comment]
Ah sorry I see what you mean now.  I used the wrong method in the UI code for the Date object.

Fixed in https://github.com/MajorMJR/factorio-server-manager/commit/f74dff6e1de81a11955aa4f2c885b16c6cbed244

**Comment by MajorMJR** [comment]
Ah my mistake, I see what you mean now.
