### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by kreekbel** [MajorMJR/factorio-server-manager#59]
current version keep changing the server-settings.json file to an outdated version, need some extra info on 0.14.16, can also not change the servers name and description or amount of players etc cause of this.

**Comment by MonkeyDrone** [comment]
I temporarily bypassed this problem by making the config file read only (linux - chmod 444).

**Comment by OnkelDom** [comment]
I have the same problem. can you make an variable for the server-settings.json?

**Comment by MajorMJR** [comment]
Hey,

Sorry for the delay, I've added some checking to use the existing server-settings.json file if found or if not then to use the default settings.  You can configure the name of the server-settings.json file in the server manager's config file if it is not the default filename.

I'll test out this patch tonight and hopefully make a bugfix release this evening.

https://github.com/MajorMJR/factorio-server-manager/commit/3931b8811f2e5acc4c8e7c5c037ecded96a4c46b

**Comment by MajorMJR** [comment]
I've added release 0.5.1 which hopefully fixes this bug.  If you could test it and see that would be appreciated.

https://github.com/MajorMJR/factorio-server-manager/releases/tag/0.5.1

**Comment by OnkelDom** [comment]
Thank you. I test ist in the next days and give you feedback.

**Comment by OnkelDom** [comment]
Ok dude i have tested it.
My config:
GS: /opt/factorio
the server-settings.json is in /opt/factorio/config/server-settings.json

i have changed the fsm config:
"settings_file": "/opt/factorio/config/server-settings.json"

1. fsm ignore thes line
2. they doesnt load my server-settings.json
3. fsm creates a file in the factorio mainfolder "server-settings.json" and i can edit there  over the gui and it saves the changes.

Thats not best practice. The edit over the gui is nice ;)

**Comment by MajorMJR** [comment]
Don't put the full path, just the name of the settings-file.  It will be saved at the root of your Factorio directory by default.

**Comment by MajorMJR** [comment]
I added a commit to move the config file from the root to the config directory.

https://github.com/MajorMJR/factorio-server-manager/commit/dfe08853e4dc4d50e1c51ce2a2256fdc4050122e

**Comment by OnkelDom** [comment]
Van you Merge it with 0.5.1? I cant build it steht the time.

**Comment by MajorMJR** [comment]
I've added version 0.5.2 which adds these bug fixes.

https://github.com/MajorMJR/factorio-server-manager/releases/tag/0.5.2
