### ISSUE TITLE
The ability to secure the webserver

### ISSUE THREAD

**Issue by Bebabo10** [MajorMJR/factorio-server-manager#6]
Can you please add a login option to be able to control the server manager.

**Comment by MajorMJR** [comment]
I'd like to add the ability to add authentication and user control eventually.  Currently a work around might be to reverse proxy the application through Apache or Nginx and add HTTP simple authentication.

**Comment by MajorMJR** [comment]
The latest 0.3 release adds authentication.  Admin user is specified in the included conf.json file.
