### ISSUE TITLE
Can't restart if server is down

### ISSUE THREAD

**Issue by drahti** [MajorMJR/factorio-server-manager#7]
Hey again :)

While tinkering around I noticed that you can get the server status into an invalid state. I loaded up the manager together with a completly empty factorio. No saves. If you start the server, you get the success message and the server starts. The server will quickly go down because it won't be able to find a save file. 

The manager UI will show the server as online though. You can't stop the server (process already finished, this is correct) as well. What is a lot worse is that you can't restart the server "Factorio server already running".

I guess that should be fixed :)

**Comment by MajorMJR** [comment]
@drahti 
Could you send me the launch command the server used when launching from the logs? Should be an easy fix, I likely just have to check if the savefile exists before starting the server.

**Comment by drahti** [comment]
copy pasted directly from server managers log:
`0.421 Error Main.cpp:340: Couldn't load the game for MP: Opening zip /opt/factorio/saves/.zip failed

0.421 Info MultiplayerManager.cpp:913: networkTick(0) mapTick(-1) changing state from(CreatingGame) to(InitializationFailed)

0.421 Error MultiplayerManager.cpp:110: MultiplayerManager failed: "Opening zip /opt/factorio/saves/.zip failed"

0.401 Loading map /opt/factorio/saves/.zip

0.400 Info MultiplayerManager.cpp:913: networkTick(0) mapTick(-1) changing state from(PreparedToHostGame) to(CreatingGame)

0.400 Info MultiplayerManager.cpp:913: networkTick(0) mapTick(-1) changing state from(Ready) to(PreparedToHostGame)

0.400 Info Router.cpp:536: Router state -> Disconnected

0.400 Info Router.cpp:509: Router peerID(65535) shutting down.

0.400 Factorio initialised

0.110 Checksum for mod base: 2829195351

0.109 Checksum for core: 3711505753

0.022 Loading mod base 0.12.31 (data.lua)

0.019 Loading mod core 0.0.0 (data.lua)

0.017 Running in headless mode

0.001 Binaries path: /opt/factorio/bin

0.001 Write data path: /opt/factorio

0.001 Read data path: /opt/factorio/data

0.001 Program arguments: "/opt/factorio/bin/x64/factorio" "--start-server" "" "--latency-ms" "100" "--autosave-interval" "5" "--autosave-slots" "10" "--port" "34197"

0.000 Operating system: Linux

0.000 2016-04-29 18:47:25; Factorio 0.12.31 (Build 18065, linux64, headless)`

**Comment by MajorMJR** [comment]
Thanks I'll fix this when I get home from work this evening.

**Comment by drahti** [comment]
No hurry at all. just wanted to let you know. Have a nice day!

**Comment by MajorMJR** [comment]
This is fixed, server will check for a savefile value in the POST request.

**Comment by jjcf89** [comment]
Reference to fix?

**Comment by MajorMJR** [comment]
Fixed in ed49b11
